FROM node:20-alpine AS base
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable

WORKDIR /app

COPY pnpm-workspace.yaml turbo.json package.json ./
COPY apps/web/package.json apps/web/package.json

RUN pnpm install --frozen-lockfile

# Copia tudo e builda só o web
COPY . .
RUN pnpm --filter ./apps/web build

# Runtime
FROM node:20-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

# Copia saída standalone do Next
COPY --from=base /app/apps/web/.next/standalone ./
COPY --from=base /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=base /app/apps/web/public ./apps/web/public

EXPOSE 3000
CMD ["node", "server.js"]
